[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1SQeQOJaBt3zCkaeralI0KToWgPwxPRK8NZi9pbNoySI/edit?gid=0#gid=0"
worksheet = "<worksheet-gid-or-folder-id>"  # worksheet GID is used when using Public Spreadsheet URL, when usign service_account it will be picked as folder_id
type = ""  # leave empty when using Public Spreadsheet URL, when using service_account -> type = "service_account"
project_id = "sapient-spark-438818-h"
private_key_id = ""
private_key = st.secrets["privatny_kluc"]
client_email = "streamlit-predikcia@sapient-spark-438818-h5.iam.gserviceaccount.com"
client_id = "101117998496772210900"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-predikcia%40sapient-spark-438818-h5.iam.gserviceaccount.com"
